import turtle
from random import randint
x = randint(10,40)
y = randint(0,360)
turtle.speed(400)
t = turtle.Turtle()
t.color("red")
t.pensize(1)
t.fillcolor("red")
t.begin_fill()
for i in range(5):
    t.speed(90)
    t.lt(144)
    t.fd(40)
t.end_fill()
t.fd(x)
t.fillcolor("red")
t.begin_fill()
for i in range(5):
    t.speed(90)
    t.lt(144)
    t.fd(40)
t.end_fill()
t.back(x)
t.right(y)
t.fd(x)
t.fillcolor("red")
t.begin_fill()
for i in range(5):
    t.speed(90)
    t.lt(144)
    t.fd(40)
t.end_fill() 
t.right(y)
t.fd(x)    
t.fillcolor("red")
t.begin_fill()
for i in range(5):
    t.speed(90)
    t.lt(144)
    t.fd(40)
t.end_fill()
t.right(y)
t.fd(400)
t.fillcolor("red")
t.begin_fill()
for i in range(5):
    t.speed(90)
    t.lt(144)
    t.fd(40)
t.end_fill()
turtle.done()