import turtle
turtle.speed(4000)
turtle.bgcolor("black")
turtle.color("red")
for i in range(40):
    turtle.fd(5*i)
    turtle.lt(90)
turtle.color("blue")
for i in range(40):
    turtle.fd(5*i)
    turtle.lt(90)
turtle.color("lightgreen")
for i in range(40):
    turtle.fd(5*i)
    turtle.lt(90)
turtle.color("yellow")
for i in range(40):
    turtle.fd(5*i)
    turtle.lt(90)
turtle.color("violet")
for i in range(40):
    turtle.fd(5*i)
    turtle.lt(90)
'''turtle.color("green")
for i in range(40):
    turtle.fd(1*i)
    turtle.lt(90)'''
turtle.penup()
turtle.goto(40,40)
turtle.pendown()
turtle.color("gold")
for i in range(40):
    turtle.fd(1*i)
    turtle.lt(90)
turtle.penup()
turtle.goto(40,40)
turtle.pendown()
turtle.color("pink")
for i in range(40):
    turtle.fd(1*i)
    turtle.lt(90)
turtle.penup()
turtle.goto(140,140)
turtle.pendown()
turtle.color("purple")
for i in range(40):
    turtle.fd(1*i)
    turtle.lt(90) 
turtle.penup()
turtle.goto(200,200)
turtle.pendown()
turtle.color("lightblue")
for i in range(40):
    turtle.fd(1*i)
    turtle.lt(90)
turtle.penup()
turtle.goto(-40,40)
turtle.pendown()
turtle.color("orange")
for i in range(40):
    turtle.fd(1*i)
    turtle.lt(90)
turtle.penup()
turtle.goto(-40,40)
turtle.pendown()
turtle.color("fuchsia")
for i in range(40):
    turtle.fd(1*i)
    turtle.lt(90)
turtle.penup()
turtle.goto(-140,140)
turtle.pendown()
turtle.color("brown")
for i in range(40):
    turtle.fd(1*i)
    turtle.lt(90)
turtle.penup()
turtle.goto(-200,200)
turtle.pendown()
turtle.color("lime")
for i in range(40):
    turtle.fd(1*i)
    turtle.lt(90)                  
turtle.penup()
turtle.goto(40,-40)
turtle.pendown()
turtle.color("darkorchid")
for i in range(40):
    turtle.fd(1*i)
    turtle.lt(90) 
turtle.penup()
turtle.goto(40,-40)
turtle.pendown()
turtle.color("dodgerblue")
for i in range(40):
    turtle.fd(1*i)
    turtle.lt(90)
turtle.penup()
turtle.goto(140,-140)
turtle.pendown()
turtle.color("aqua")
for i in range(40):
    turtle.fd(1*i)
    turtle.lt(90)
turtle.penup()
turtle.goto(200,-200)
turtle.pendown()
turtle.color("silver")
for i in range(40):
    turtle.fd(1*i)
    turtle.lt(90)
turtle.penup()
turtle.goto(-40,-25)
turtle.pendown()
turtle.color("black")
turtle.write("THE END",font=("courier",33,"italic"))                                      
turtle.done()