import turtle
turtle.bgcolor("black")
turtle.speed(4000)
#for i in range(2):
for i in range(140):
        turtle.pencolor("aqua")
        turtle.circle(1+i)
        turtle.fd(2)
        turtle.right(1)
turtle.goto(0,0)
for i in range(40):
    turtle.pencolor("blue")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(140):
    turtle.pencolor("red")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(40):
        turtle.pencolor("lightgreen")
        turtle.circle(1+i)
        turtle.fd(2)
        turtle.right(1)
turtle.goto(0,0)
for i in range(140):
    turtle.pencolor("pink")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)   
turtle.goto(0,0)
for i in range(40):
    turtle.pencolor("orange")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)  
turtle.goto(0,0)
for i in range(140):
        turtle.pencolor("aqua")
        turtle.circle(1+i)
        turtle.fd(2)
        turtle.right(1)      
turtle.goto(0,0)
for i in range(40):
    turtle.pencolor("blue")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(140):
    turtle.pencolor("red")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(40):
        turtle.pencolor("lightgreen")
        turtle.circle(1+i)
        turtle.fd(2)
        turtle.right(1)
turtle.goto(0,0)
for i in range(140):
    turtle.pencolor("pink")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(40):
    turtle.pencolor("orange")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(140):
        turtle.pencolor("aqua")
        turtle.circle(1+i)
        turtle.fd(2)
        turtle.right(1)
turtle.goto(0,0)
for i in range(40):
    turtle.pencolor("blue")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(140):
    turtle.pencolor("red")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(40):
        turtle.pencolor("lightgreen")
        turtle.circle(1+i)
        turtle.fd(2)
        turtle.right(1)
turtle.goto(0,0)
for i in range(140):
    turtle.pencolor("pink")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(40):
    turtle.pencolor("orange")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(140):
        turtle.pencolor("aqua")
        turtle.circle(1+i)
        turtle.fd(2)
        turtle.right(1)
turtle.goto(0,0)
for i in range(40):
    turtle.pencolor("blue")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(140):
    turtle.pencolor("red")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(40):
        turtle.pencolor("lightgreen")
        turtle.circle(1+i)
        turtle.fd(2)
        turtle.right(1)
turtle.goto(0,0)
for i in range(140):
    turtle.pencolor("pink")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(40):
    turtle.pencolor("orange")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(140):
        turtle.pencolor("aqua")
        turtle.circle(1+i)
        turtle.fd(2)
        turtle.right(1)
turtle.goto(0,0)
for i in range(40):
    turtle.pencolor("blue")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(140):
    turtle.pencolor("red")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(40):
        turtle.pencolor("lightgreen")
        turtle.circle(1+i)
        turtle.fd(2)
        turtle.right(1)
turtle.goto(0,0)
for i in range(140):
    turtle.pencolor("pink")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
for i in range(40):
    turtle.pencolor("orange")
    turtle.circle(1+i)
    turtle.fd(2)
    turtle.right(1)
turtle.goto(0,0)
turtle.done()
